# kompilator c
CCOMP = gcc

# konsolidator
LOADER = gcc

OPT = -g -DDBUG

pub_sym_1: pub_sym_1.o
	$(LOADER) $(OPT) pub_sym_1.o -o  pub_sym_1
 
pub_sym_1.o: pub_sym_1.c
	$(CCOMP) -c $(OPT) pub_sym_1.c
	
	
pub_sym_1_v1: pub_sym_1_v1.o
	$(LOADER) $(OPT) pub_sym_1_v1.o -o  pub_sym_1_v1
 
pub_sym_1_v1.o: pub_sym_1_v1.c
	$(CCOMP) -c $(OPT) pub_sym_1_v1.c
	
pub_sym_1_v2: pub_sym_1_v2.o
	$(LOADER) $(OPT) pub_sym_1_v2.o -o  pub_sym_1_v2
 
pub_sym_1_v2.o: pub_sym_1_v2.c
	$(CCOMP) -c $(OPT) pub_sym_1_v2.c

pub_sym_1_v3: pub_sym_1_v3.o
	$(LOADER) $(OPT) pub_sym_1_v3.o -o  pub_sym_1_v3
 
pub_sym_1_v3.o: pub_sym_1_v3.c
	$(CCOMP) -c $(OPT) pub_sym_1_v3.c
